name: Docker Image CI

on:
  push:
    branches: [ "add_uptime_ratio" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: What
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: sir-bruno-hyppo
          password: ${{ secrets.GH_TOKEN_BOT }}
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/startupflow/uptimerobot_exporter:${{ env.BRANCH }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
